export const SHOWPRODUCTLIST = "SHOW_PRODUCT_LIST";
export const SHOWPRODUCTDETAIL = "SHOW_PRODUCT_DETAIL";

export const SHOWCARTLIST = "SHOW_CART_LIST";
export const INCREMENTCART = "INCREMENT_CART"
export const DECREMENTCART = "DECREMENT_CART"
export const DELETECART = "DELETE_CART"