export const FETCH_PRODUCT_LIST_DATA = "FETCH_PRODUCT_LIST_DATA";
export const FETCH_PRODUCT_DETAIL_DATA = "FETCH_PRODUCT_DETAIL_DATA";

export const SHOWCARTLIST = "SHOW_CART_LIST";
export const INCREMENTCART = "INCREMENT_CART";
export const DECREMENTCART = "DECREMENT_CART";
export const DELETECART = "DELETE_CART";
