export const FETCH_PRODUCT_LIST_DATA = "FETCH_PRODUCT_LIST_DATA";
export const FETCH_PRODUCT_DETAIL_DATA = "FETCH_PRODUCT_DETAIL_DATA";

export const FETCH_CART_LIST_DATA = "FETCH_CART_LIST_DATA";
export const STORE_CART_DATA = "STORE_CART_DATA";
export const INCREMENT_CART_DATA = "INCREMENT_CART_DATA";
export const DECREMENT_CART_DATA = "DECREMENT_CART_DATA";
export const UPDATE_CART_DATA = "UPDATE_CART_DATA";
export const DELETE_CART_DATA = "DELETE_CART_DATA";
export const DELETE_CART_ITEM = "DELETE_CART_ITEM";

export const FETCH_USER_DATA = "FETCH_USER_DATA";
export const STORE_USER_DATA = "STORE_USER_DATA";
